spring:
  datasource:
    url: jdbc:postgresql://localhost:8085/mydb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
  mail:
    host: ${MAIL_SENDER_HOST}
    port: ${MAIL_SENDER_PORT}
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        transport:
          protocol: ${MAIL_SENDER_PROTOCOL}
        debug: false
        smtp:
          ssl:
            enable: ${MAIL_SENDER_SSL}
          auth: ${MAIL_SENDER_AUTH}
          starttls:
            enable: ${MAIL_SENDER_STARTTLS_ENABLE}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
features:
  upload:
    default-region: "CZ"
    batch-size: 50
  upsert:
    max-company-limit: 200000
    page-size: 50
    chunk-size: 10
    fixed-delay: "300000" # 5 minutes
    initial-delay: "20000" # 20 seconds
    notification-email: ${UPSERT_NOTIFICATION_EMAIL}

rcrm:
  username: ${RCRM_USERNAME}
  api-key: ${RCRM_API_KEY}
  base-url: ${RCRM_BASE_URL}
  instance-name: ${RCRM_INSTANCE_NAME}
  max-daily-calls: 24000

logging:
  level:
    dev.lobanov.raynetassignment: INFO